// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Bar: typeof import('./src/components/Front/Home/Bar.vue')['default']
    Class: typeof import('./src/components/Front/Header/Class.vue')['default']
    Dplayer: typeof import('./src/components/Front/Play/Dplayer.vue')['default']
    Front: typeof import('./src/components/Front.vue')['default']
    Header: typeof import('./src/components/Front/Header/Header.vue')['default']
    Home: typeof import('./src/components/Front/Home.vue')['default']
    HomeChild: typeof import('./src/components/Front/Home/HomeChild.vue')['default']
    ImgLazy: typeof import('./src/components/Front/SearchResult/imgLazy.vue')['default']
    Mv: typeof import('./src/components/Front/PublicComponents/Mv.vue')['default']
    NBackTop: typeof import('naive-ui')['NBackTop']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NDialogProvider: typeof import('naive-ui')['NDialogProvider']
    NEllipsis: typeof import('naive-ui')['NEllipsis']
    NGrid: typeof import('naive-ui')['NGrid']
    NGridItem: typeof import('naive-ui')['NGridItem']
    NIcon: typeof import('naive-ui')['NIcon']
    NImage: typeof import('naive-ui')['NImage']
    NInput: typeof import('naive-ui')['NInput']
    NList: typeof import('naive-ui')['NList']
    NListItem: typeof import('naive-ui')['NListItem']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NNotificationProvider: typeof import('naive-ui')['NNotificationProvider']
    NPagination: typeof import('naive-ui')['NPagination']
    NScrollbar: typeof import('naive-ui')['NScrollbar']
    NSkeleton: typeof import('naive-ui')['NSkeleton']
    NSpace: typeof import('naive-ui')['NSpace']
    NSpin: typeof import('naive-ui')['NSpin']
    NThing: typeof import('naive-ui')['NThing']
    Play: typeof import('./src/components/Front/Play.vue')['default']
    PlayMsg: typeof import('./src/components/Front/Play/PlayMsg.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./src/components/Front/Search.vue')['default']
    Searcher: typeof import('./src/components/Front/Header/Searcher.vue')['default']
    SearchResult: typeof import('./src/components/Front/SearchResult/SearchResult.vue')['default']
    SearchTmp: typeof import('./src/components/Front/SearchResult/SearchTmp.vue')['default']
  }
}

export {}
