// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Bar: typeof import('./src/components/Home/Bar.vue')['default']
    Class: typeof import('./src/components/Header/Class.vue')['default']
    Dplayer: typeof import('./src/components/Play/Dplayer.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    Home: typeof import('./src/components/Home.vue')['default']
    HomeChild: typeof import('./src/components/Home/HomeChild.vue')['default']
    ImgLazy: typeof import('./src/components/SearchResult/imgLazy.vue')['default']
    Mv: typeof import('./src/components/PublicComponents/Mv.vue')['default']
    NBackTop: typeof import('naive-ui')['NBackTop']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NDropdown: typeof import('naive-ui')['NDropdown']
    NEllipsis: typeof import('naive-ui')['NEllipsis']
    NGrid: typeof import('naive-ui')['NGrid']
    NGridItem: typeof import('naive-ui')['NGridItem']
    NIcon: typeof import('naive-ui')['NIcon']
    NImage: typeof import('naive-ui')['NImage']
    NInput: typeof import('naive-ui')['NInput']
    NList: typeof import('naive-ui')['NList']
    NListItem: typeof import('naive-ui')['NListItem']
    NPagination: typeof import('naive-ui')['NPagination']
    NScrollbar: typeof import('naive-ui')['NScrollbar']
    NSkeleton: typeof import('naive-ui')['NSkeleton']
    NSpace: typeof import('naive-ui')['NSpace']
    NSpin: typeof import('naive-ui')['NSpin']
    NThing: typeof import('naive-ui')['NThing']
    Play: typeof import('./src/components/Play.vue')['default']
    PlayMsg: typeof import('./src/components/Play/PlayMsg.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./src/components/Search.vue')['default']
    Searcher: typeof import('./src/components/Header/Searcher.vue')['default']
    SearchResult: typeof import('./src/components/SearchResult/SearchResult.vue')['default']
    SearchTmp: typeof import('./src/components/SearchResult/SearchTmp.vue')['default']
  }
}

export {}
